version: '3.5'
services:
  web:
    build: .
    ports: 
    - "8000:8000"
    container_name: mrph_demo
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4'
    #       memory: 16G
    restart: unless-stopped